---
ansible_user: "{{ lookup('env', 'USER') }}"
ansible_group: staff

home_dir: "/Users/{{ ansible_user }}"
soft_dir: "{{ home_dir }}/software"
tmp_install_dir: "{{ home_dir }}/tmp"
projects_dir: "{{ home_dir }}/projects"
bin_dir: "{{ home_dir }}/bin"
create_folders:
  - "{{ soft_dir }}"
  - "{{ tmp_install_dir }}"
  - "{{ projects_dir }}"
  - "{{ bin_dir }}"

rsync_sync_src_dest: []

homeschick_repositories:
  - { url: "https://github.com/alexsavio/dotfiles.git", branch: "m1" }

homebrew_repos:
  - alajmo/mani
  - homebrew/cask-fonts

homebrew_cask_packages:
  # - anki
  - aws-vault
  - caffeine
  - cmake
  # - cyberduck
  # - dropbox
  # - fing
  - firefox
  - font-jetbrains-mono
  - font-jetbrains-mono-nerd-font
  - font-ubuntu-mono
  - font-ubuntu-mono-nerd-font
  - google-chrome
  - google-cloud-sdk
  - google-drive
  # - inkscape
  - iterm2
  - keepassxc
  # - lyx
  # - mactex
  # - megasync
  - meld
  - ngrok
  - obsidian
  - rectangle
  # - slack
  # - spotify
  # - telegram
  # - transmission
  # - transmission-remote-gui
  # - tunnelblick
  # - virtualbox
  - visual-studio-code
  - vlc
  # - vscodium
  # - zoom

mas_packages: []
# - 497799835 # xcode
# - 937984704 # Amphetamine
# - 441258766 # Magnet

homebrew_packages:
  - ack
  - asdf
  - autoconf
  - autojump
  - automake
  - aws-iam-authenticator
  - awscli
  - bandwhich
  - bfg
  - bottom
  - cairo
  - cloc
  - coreutils
  - curl
  - direnv
  - dive
  - dnsmasq
  - docker
  - docker-compose
  - docker-credential-helper
  - docker-machine
  - enchant
  - entr
  - exiftool
  - fasd
  - fdupes
  - ffmpeg
  - freetype
  - fswatch
  - fzf
  - gdal
  - gdbm
  - giflib
  - git
  - git-delta
  - github/gh/gh
  - gnu-time
  - goaccess
  - gpg
  - graphicsmagick
  - htop
  - hyperfine
  - imagemagick@6
  - inetutils
  - jhead
  - jpeg
  - jpeg
  - jq
  - lesspipe
  - libevent
  - libffi
  - libjpeg
  - libpng
  - librsvg
  - libsvg-cairo
  - libtool
  - libxslt
  - libyaml
  - mas
  - mani
  - ncdu
  - nginx
  - nodenv
  - nvm
  - openssl
  - ossp-uuid
  - packer
  - pandoc
  - pango
  - pass
  - pipx
  - pkg-config
  - pkg-config
  - podman
  - postgresql
  - pre-commit
  - pwgen
  - pyenv
  - pyenv-virtualenv
  - python
  - qpdf
  - ranger
  - rcm
  - readline
  - redis
  - ripsecrets
  - rsync
  - rtmpdump
  - rustdesk
  - shellcheck
  - sqlite3
  - ssh-copy-id
  - esolitos/ipa/sshpass
  - swig
  - tcl-tk
  - tealdeer
  - terraform
  - tig
  - tmux
  - topgrade
  - tree
  - unzip
  - vim
  - watch
  - watchman
  - wget
  - xz
  - yank
  - zlib
  - zsh
  - zsh-completions
  - zsh-history-substring-search

cargo_packages:
  - bat
  - broot
  - calc
  # - cloak
  - clog-cli
  - coreutils
  - diskonaut
  - ddh
  - drill
  - dtool
  - exa
  - fblog
  - fend
  - git-cliff
  - git-journal
  - git-tidy
  - gitui
  - grex
  - kalker
  - lsd
  - starship
  - tealdeer
  - termscp
  - ttdl
  - watchexec-cli
  - zoxide
  - rm-improved
  - xcp
  - du-dust
  - ripgrep
  - fd-find
  - sd
  - procs
  - tokei
  - xh
  - monolith
  - nushell
  - bdt
  - just
  - pyflow
  - pylyzer

pyenv_python_versions:
  - 3.10.12

pip_packages:
  - black
  - boto
  - boto3
  - build
  - flake8
  - ipython
  - lifelogger
  - pdbpp
  - poetry
  - pygments
  - python-language-server
  - pyyaml
  - requests
  - s3cmd
  - virtualenv
  - wheel

pipx_packages:
  - httpie
  - csvkit
  - tsrc

vscode_extensions:
  - 2gua.rainbow-brackets
  - 4ops.terraform
  - alefragnani.Bookmarks
  - amazonwebservices.aws-toolkit-vscode
  - arcticicestudio.nord-visual-studio-code
  - Cameron.vscode-pytest
  - chenzhe.split-line
  - chrmarti.regex
  - dhoeric.ansible-vault
  - donjayamanne.githistory
  - DotJoshJohnson.xml
  - eamodio.gitlens
  - EditorConfig.EditorConfig
  - erd0s.terraform-autocomplete
  - esbenp.prettier-vscode
  - GitHub.copilot
  - GitHub.vscode-pull-request-github
  - googlecloudtools.cloudcode
  - hashicorp.terraform
  - lmcarreiro.vscode-smart-column-indenter
  - ms-azuretools.vscode-docker
  - ms-python.python
  - ms-python.vscode-pylance
  - ms-toolsai.jupyter
  - ms-toolsai.jupyter-keymap
  - ms-toolsai.jupyter-renderers
  - ms-vscode-remote.remote-ssh
  - ms-vscode-remote.remote-ssh-edit
  - octref.vetur
  - oderwat.indent-rainbow
  - Perkovec.emoji
  - redhat.vscode-yaml
  - ritwickdey.LiveServer
  - rust-lang.rust
  - sdras.night-owl
  - sleistner.vscode-fileutils
  - stuart.unique-window-colors
  - taniarascia.new-moon-vscode
  - vscode-icons-team.vscode-icons
  - wwm.better-align
  - yzhang.markdown-all-in-one
  - zhuangtongfa.material-theme

asdf_plugins:
  - python
  - direnv
  - nodejs https://github.com/asdf-vm/asdf-nodejs.git
  - poetry https://github.com/asdf-community/asdf-poetry.git
