---
- name: Install homebrew
  include_role:
    name: geerlingguy.mac.homebrew

- name: Make sure homebrew bin is in path
  ansible.builtin.lineinfile:
    path: /etc/paths
    state: present
    line: "/opt/homebrew/bin"
  become: true
  become_user: root

- name: Add custom homebrew repos
  community.general.homebrew_tap:
    name: "{{ homebrew_repos }}"

# - name: Install core packages via brew casks
#   community.general.homebrew_cask:
#     name: "{{ item }}"
#   ignore_errors: yes
#   with_items:
#     "{{ homebrew_cask_packages }}"

- name: Install homebrew packages
  community.general.homebrew:
    name: "{{ item }}"
    state: present
    update_homebrew: yes
  with_items: "{{ homebrew_packages }}"

- name: Install from Mac app store
  shell: mas install {{ item }}
  with_items: "{{ mas_packages }}"
