---

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_group }}"
  loop:
    "{{ create_folders }}"
  become: yes
  become_method: sudo
