---

- name: python versions
  shell: source ~/.zshrc && pyenv install {{ item }}
  environment:
    CONFIGURE_OPTS: --enable-optimizations
  loop: '{{ pyenv_python_versions }}'
  tags:
  - pyenv

- name: python versions active
  shell: pyenv global {{ pyenv_python_versions | join(" ") }}
  tags:
  - pyenv

- name: pyenv rehash
  shell: pyenv rehash
  tags:
  - pyenv

- name: python versions latest build requirements
  pip:
    name:
    - pip
    - setuptools
    - virtualenv
    state: latest
    executable: '~/.pyenv/versions/{{ item }}/bin/pip{% if "pypy3" in item %}3{% endif %}'
  environment:
    PIP_REQUIRE_VIRTUALENV: ""
  loop: '{{ pyenv_python_versions }}'
  tags:
  - pyenv

- name: virtualenv update embed wheels
  shell: ~/.pyenv/versions/{{ pyenv_python_versions[0] }}/bin/python -m virtualenv --upgrade-embed-wheels
  environment:
    PIP_REQUIRE_VIRTUALENV: ""
  tags:
  - pyenv

- name: Install pip packages
  pip:
    name: '{{ pip_packages }}'
    state: latest
    executable: '~/.pyenv/versions/{{ pyenv_python_versions[0] }}/bin/pip'
  environment:
    PIP_REQUIRE_VIRTUALENV: ""
  tags:
  - pyenv

- name: pyenv rehash
  shell: pyenv rehash
  tags:
  - pyenv
